### ISSUE TITLE
О настройке уведомлений в казне, связанных с мобами

### ISSUE THREAD

**Issue by pavelgivoy** [VioletTape/Kazna#4]
1) Проблемы с настройками уведомлений на мобов. Они вновь становятся дефолтными при любом взаимодействии с казной, связанном с механикой мобов (принятие форварда ботом, нажатие на любую из кнопок в боте и т.д.)
2) Можно ли как-то убрать ограничение на максимальный и минимальный уровень мобов в пингах?

**Comment by VioletTape** [comment]
Лучше все же писать на пожелания и баги разные тикеты
