### ISSUE TITLE
Уведомление о восстановлении хп

### ISSUE THREAD

**Issue by Ricoroma** [VioletTape/Kazna#7]
**Какую проблему новая фича решает?**
Когда умер от мобов или на арене и хочешь знать, когда можно идти в квест (реген мин хп) или когда фул хп регеен
**Опишите желаемое поведение бота**
Присылать уведомление, когда отрегенилось минимальное хп и/или фул хп

**Есть ли альтернативное решение**
Хз

**Дополнительная информация**

🏅  5 - 14  ❤️78
🏅15 - 24  ❤️105
🏅25 - 34  ❤️124
🏅35 - 44  ❤️162
🏅45 - 54  ❤️228
🏅55 - 64  ❤️228
🏅65+       ❤️325

**Comment by VioletTape** [comment]
Готово
